name: Default Master/Main Workflow

on:
    push:
        branches:
            - main
            - master
        paths:
            - '**.py'

jobs:
    test:
        uses: ./.github/workflows/python.unit-tests.yaml
        with:
            python-version: "3.9"
            os: ubuntu-latest
    build:
        uses: ./.github/workflows/python.build-artefact.yaml
        needs: test
