name: Default Development Workflow

on:
    push:
        branches:
            - dev
            - '**/feat**'
            - '**/fix**'
        paths:
            - '**.py'
            - '!**.md'

jobs:
    test:
        uses: ./.github/workflows/python.unit-tests.yaml
        with:
            python-version: "3.9"
            os: ubuntu-latest
